name: Linter workflow

on:
    pull_request:
        branches: [ master ]

jobs:
    run_conventional_commit:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./server
        steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - uses: actions/setup-node@v1
          with:
            node-version: 10.*
        - run: npm install
        - run: npx commitlint --from HEAD~${{ github.event.pull_request.commits }} --to HEAD

    run_eslint_on_server:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./server
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 10.*
        - run: npm install
        - run: npm run lint
    
    run_eslint_on_client:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./server/client
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 10.*

        - run: npm install
        - run: npm run lint
